### ISSUE TITLE
MacInterface Yang Error 

### ISSUE THREAD

**Issue by sbarguil** [openBackhaul/macInterface#16] opened 2019-08-28 09:30 UTC
Mac Interface Yang problems to compile:

pyang -f tree mac-interface.yang 
mac-interface.yang:1: error: syntax error: illegal keyword: ﻿module mac-interface {

Error in parsing module

**Comment by alexandrustancu** [comment] 2020-01-16 10:45
I believe this is a problem caused by the YANG file being edited under Windows.

You could try the following command first, and then re-run your pyang:

`dos2unix -o mac-interface.yang`

It worked for me.

**Comment by sbarguil** [comment] 2020-01-16 10:56
Hi. I'm using linux env. The yang also generates errror if I try to
visualize it in yang suite.

**Comment by alexandrustancu** [comment] 2020-01-16 10:59
It's great that you are using Linux env. The issue is that the person who created the YANG most probably used a Windows env.

This is why you should just run the command that I've suggested:

`dos2unix -o mac-interface.yang`

And everything should be fine.

**Comment by sbarguil** [comment] 2020-01-16 11:06
Thanks. I'll check it out and let you know if I have any questions

**Comment by alexandrustancu** [comment] 2021-01-21 15:55
This is addressed in the UML2YANG tool and does not happen anymore.

**Comment by openBackhaul** [comment] 2021-01-21 17:39
Many thanks!

**Closed as completed by openBackhaul** 2021-01-21 17:39 UTC
